#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


DEFAULT_SPEC = {
    "units": "m",
    "site": {"width": 30, "depth": 40},
    "building": {"width": 14, "depth": 18, "floors": 4, "floor_height": 3.2},
    "setbacks": {"front": 5, "rear": 4, "left": 3, "right": 3},
    "materials": {
        "site": "site_matte_gray",
        "building": "warm_concrete",
        "glass": "concept_glass",
    },
    "scenes": ["Vaziyet", "Genel Perspektif", "Ön Cephe"],
    "output_skp": "concept_massing.skp",
}


def load_spec(path):
    if not path:
        return DEFAULT_SPEC
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    merged = json.loads(json.dumps(DEFAULT_SPEC))
    for key, value in data.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key].update(value)
        else:
            merged[key] = value
    return merged


def ruby_string(value):
    return json.dumps(str(value), ensure_ascii=False)


def generate_ruby(spec):
    site = spec["site"]
    building = spec["building"]
    setbacks = spec["setbacks"]
    materials = spec["materials"]
    scenes = spec.get("scenes", [])
    output_skp = spec.get("output_skp", "concept_massing.skp")

    width = float(building["width"])
    depth = float(building["depth"])
    floors = int(building["floors"])
    floor_height = float(building["floor_height"])
    total_height = floors * floor_height
    x0 = float(setbacks.get("left", 0))
    y0 = float(setbacks.get("front", 0))

    return f'''# encoding: UTF-8
# Generated by sketchup-konsept-ve-kutle-modelleme.
# Run inside SketchUp desktop, for example:
# SketchUp.exe -RubyStartup "C:/path/to/sketchup_massing_scene.rb"

model = Sketchup.active_model
model.start_operation("Concept Massing", true)

begin
  entities = model.entities
  materials = model.materials
  layers = model.layers

  site_tag = layers.add("00_site")
  mass_tag = layers.add("10_building_massing")
  marker_tag = layers.add("20_concept_markers")

  site_mat = materials.add({ruby_string(materials.get("site", "site_matte_gray"))})
  site_mat.color = Sketchup::Color.new(185, 185, 178)
  building_mat = materials.add({ruby_string(materials.get("building", "warm_concrete"))})
  building_mat.color = Sketchup::Color.new(198, 188, 172)
  glass_mat = materials.add({ruby_string(materials.get("glass", "concept_glass"))})
  glass_mat.color = Sketchup::Color.new(120, 170, 205)
  glass_mat.alpha = 0.55

  site_group = entities.add_group
  site_group.name = "site_plane"
  site_group.layer = site_tag
  site_face = site_group.entities.add_face(
    [0.m, 0.m, 0.m],
    [{float(site["width"])}.m, 0.m, 0.m],
    [{float(site["width"])}.m, {float(site["depth"])}.m, 0.m],
    [0.m, {float(site["depth"])}.m, 0.m]
  )
  site_face.material = site_mat

  mass_group = entities.add_group
  mass_group.name = "building_massing_{floors}_floors"
  mass_group.layer = mass_tag
  base = [
    [{x0}.m, {y0}.m, 0.m],
    [{x0 + width}.m, {y0}.m, 0.m],
    [{x0 + width}.m, {y0 + depth}.m, 0.m],
    [{x0}.m, {y0 + depth}.m, 0.m]
  ]
  face = mass_group.entities.add_face(base)
  face.material = building_mat
  face.pushpull({total_height}.m)

  (1...{floors}).each do |floor|
    z = floor * {floor_height}.m
    line = mass_group.entities.add_line([{x0}.m, {y0 - 0.15}.m, z], [{x0 + width}.m, {y0 - 0.15}.m, z])
    line.layer = marker_tag
  end

  entry_group = entities.add_group
  entry_group.name = "concept_entry_marker"
  entry_group.layer = marker_tag
  entry_face = entry_group.entities.add_face(
    [{x0 + width * 0.4}.m, {y0 - 0.05}.m, 0.m],
    [{x0 + width * 0.6}.m, {y0 - 0.05}.m, 0.m],
    [{x0 + width * 0.6}.m, {y0 - 0.05}.m, 2.4.m],
    [{x0 + width * 0.4}.m, {y0 - 0.05}.m, 2.4.m]
  )
  entry_face.material = glass_mat

  pages = model.pages
{chr(10).join(f'  pages.add({ruby_string(scene)})' for scene in scenes)}

  model.set_attribute("construction_ai", "units", {ruby_string(spec.get("units", "m"))})
  model.set_attribute("construction_ai", "qa_note", "Concept massing only; verify planning, structure, code and fabrication before use.")

  base_output_path = File.expand_path({ruby_string(output_skp)}, File.dirname(__FILE__))
  output_path = base_output_path
  if File.exist?(output_path)
    stem = File.basename(output_path, ".*")
    ext = File.extname(output_path)
    timestamp = Time.now.strftime("%Y%m%d_%H%M%S")
    output_path = File.join(File.dirname(output_path), "#{{stem}}_#{{timestamp}}#{{ext}}")
  end
  model.save(output_path)
  puts "Saved SketchUp concept massing to #{{output_path}}"
  model.commit_operation
rescue => error
  model.abort_operation
  puts "SketchUp massing generation failed: #{{error.class}} - #{{error.message}}"
  puts error.backtrace.join("\\n")
end
'''


def main():
    parser = argparse.ArgumentParser(description="Generate a SketchUp Ruby massing script from JSON spec.")
    parser.add_argument("--spec", help="JSON spec path. Uses a default sample if omitted.")
    parser.add_argument("--output", default="sketchup_massing_scene.rb")
    args = parser.parse_args()

    spec = load_spec(args.spec)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_ruby(spec), encoding="utf-8")
    print(json.dumps({"ruby_script": str(output), "spec": spec}, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
